version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: subscription_local_postgres
    restart: always
    environment:
      POSTGRES_USER: subsuser
      POSTGRES_PASSWORD: subspass
      POSTGRES_DB: subsdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/001_create_subscriptions.sql:/docker-entrypoint-initdb.d/001_create_subscriptions.sql

  subscription-service:
    build: .
    container_name: subscription_service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata: